### ISSUE TITLE
如何取消鼠标指向时滚动效果？

### ISSUE THREAD

**Issue by muguiping** [overtrue/wp-auto-top#1]
如何取消鼠标指向时滚动效果？我把数值设置为“0”或者“-999999999”，鼠标指向的时候它都会移动，怎么办？

**Comment by overtrue** [comment]
已经加了一个选项，你更新版本试试。

**Comment by muguiping** [comment]
效率太高了，谢谢谢谢！

**Comment by muguiping** [comment]
抱歉，再次打扰。
滚动图标中间的“浏览评论”链接，我想改为任意链接，是否可行？比如我想通过点击中间这个图标跳转至/404.HTML。

**Comment by overtrue** [comment]
@muguiping 抱歉，这些定制你可能需要自己开发了，我现在工作太忙，已经不维护这些插件了。

**Comment by muguiping** [comment]
好的，谢谢！
